import type { Metadata } from 'next';
import { gigaSans } from '@/app/fonts';
import './globals.css';
import { Header } from '@/components/header';
import { auth } from '@/config/auth';

export const metadata: Metadata = {
    title: 'UProffi - работа в удовольствие это реально',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth();
    return (
        <html lang="en">
            <body className={`${gigaSans.variable} font-sans`}>
                <Header />
                <h3>{session?.user?.name}</h3>
                {children}
            </body>
        </html>
    );
}
